### ISSUE TITLE
Programmatic Access got exception "API Catalog version doesn't match. Found 10, expected 9."

### ISSUE THREAD

**Issue by libihan** [dotnet/apisof.net#66]
I followed [Programmatic Access](https://github.com/dotnet/apisof.net/blob/main/docs/upgrade-planner/programmatic-access.md) to use this tool programmatically. But hit exception below

`var catalog = await ApiCatalogModel.LoadFromWebAsync();`
```
System.IO.InvalidDataException
  HResult=0x80131501
  Message=API Catalog version doesn't match. Found 10, expected 9.
  Source=Terrajobst.ApiCatalog
  StackTrace:
   at Terrajobst.ApiCatalog.ApiCatalogModel.<LoadAsync>d__94.MoveNext()
   at Terrajobst.ApiCatalog.ApiCatalogModel.<LoadFromWebAsync>d__91.MoveNext()
   at Terrajobst.ApiCatalog.ApiCatalogModel.<LoadFromWebAsync>d__91.MoveNext()
   at Terrajobst.ApiCatalog.ApiCatalogModel.<LoadFromWebAsync>d__91.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in Q:\source\ConsoleApp1\ConsoleApp1\Program.cs:line 13
```

**Comment by terrajobst** [comment]
I just published a new version of the package that will address that.
